<a href="https://colab.research.google.com/github/stefaniemeliss/Python_Data_Science/blob/main/01_Python_DS_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

In [202]:
# import
import numpy as np

In Python, types of variables are automatically inferred. 

Lists can be created based on heterogeneous elements (e.g., bool, str, float, int) and are then referred to as *dynamic-type* list.

Lists with homogeneous elements are referred to as *fixed-type* list and computationally more efficient as they only need one pointer to a continous block of data, but also lack flexibility.

To create arrays in Python, the built-in **array** module can be used.

In NumPy, **ndarray** object stores data efficiently and ands operations to it (i.e., methods). 

## NumPy Arrays

In [203]:
# create array from python list
np.array([1, 4, 2, 5, 3])  

array([1, 4, 2, 5, 3])

However, ndarrays can only store data of the same type and will upscale if possible (i.e., from integer to float).

In [204]:
# upscaling from integer to float
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Data type can also explicitely be specified.

In [205]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

NumPy arrays can also be multidimensional.

In [206]:
# create multidimensional array using nested lists
np.array([range(i, i + 3) for i in [2, 4, 6]])
# for each i, create an array ranging from i to excluding i + 3

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

There are several routins built into NumPy to create arrays.

In [207]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [208]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [209]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [210]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [211]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [212]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.95884927, 0.17809462, 0.61130112],
       [0.7044003 , 0.89172417, 0.51511729],
       [0.73705298, 0.17818634, 0.24485169]])

In [213]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.59773649,  0.21182799,  0.81131318],
       [-0.64544226,  0.6196507 ,  0.79309108],
       [-1.22073533, -0.83303769, -1.59226632]])

In [214]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.36469538, -0.40030603, -0.71114687],
       [-0.34223102,  0.4368197 , -0.58348496],
       [-1.55200935, -0.11602464,  1.79654673]])

In [215]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[0, 6, 4],
       [9, 1, 2],
       [2, 7, 9]])

In [216]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [217]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

## NumPy Standard Data Types
NumPy arrays contain values of a single type, so it is important to have detailed
knowledge of those types and their limitations. The datatype of the array can be assigned using a character string.

*   bool_ - Boolean (True or False) stored as a byte
*   int_ - Default integer type (same as C long; normally either int64 or int32) 
*   unit_ - Shorthand for unsigned integer
*   float_ - Shorthand for float64
*   complex_ - Shorthand for complex128

## Basics of NumPy Arrays

Data manipulation in Python often synonymous to wrangling data in NumPy.

*   *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
*   *Indexing of arrays*: Getting and setting the value of individual array elements
*   *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
*   *Reshaping of arrays*: Changing the shape of a given array
*   *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

### NumPy Array Attributes


In [218]:
# create three random arrays
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

*   ndim (number of dimensions)
*   shape (size of each dimension)
*   size (total size of the array)
*   dtype (data type)
*   itemsize (size (in bytes) of each array element)
*   nbytes (total size (in bytes) of the array)

In [219]:
# access information about attributes
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes") # nbytes is equal to itemsize times size

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


### Array Indexing

NumPy indexing largely overlaps with Python's indexing: In a one-dimensional array, one can access the ith value(counting from zero) by specifying the desired index in square brackets, just as with Python lists.

In [220]:
x1

array([5, 0, 3, 3, 7, 9])

In [221]:
x1[0]

5

In [222]:
x1[4]

7

To index from the end of the array, one can use negative indices

In [223]:
x1[-1]

9

In [224]:
x1[-2]

7

In a multidimensional array, one accesses items using a comma-separated tuple of
indices.

In [225]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [226]:
x2[0,0]

3

In [227]:
x2[2,0]

1

In [228]:
x2[2,-1]

7

Indexing can also be used to modify values at the indexed position.

In [229]:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

CAVEAT: Unlike Python lists, NumPy arrays have a fixed type. This means,
for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. 

In [230]:
x1[0] = 3.14159 # this will be truncated to 3 (but not rounded)!
x1

array([3, 0, 3, 3, 7, 9])

### Array Slicing: Accessing Subarrays

Slicing provides access to subarrays with the slice nottion, marked by the colon (:) character.

x[start:stop:step]

If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1.

In [231]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [232]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [233]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [234]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [235]:
x[4:7] # middle subarray

array([4, 5, 6])

In [236]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [237]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

When the step value is negative, the
defaults for start and stop are swapped. This becomes a convenient way to reverse
an array.

In [238]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [239]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

Multidimensional slices work in the same way, with multiple slices separated by commas.

In [240]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [241]:
x2[:2, :3] # two rows: until excluding row 2 counting from 0
# three columns: until excluding column 3 counting from 0

array([[12,  5,  2],
       [ 7,  6,  8]])

In [242]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [243]:
x2[::-1, ::-1] # subarray dimensions can even be reversed together

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [244]:
print(x2[:, 0]) # whole first column of x2

[12  7  1]


In [245]:
print(x2[0, :]) # whole first row of x2

[12  5  2  4]


In [246]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


Array slices return views rather than copies of the array data. 

This default behavior means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

In [247]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [248]:
x2_sub = x2[:2, :2] # extract a 2×2 subarray from x2
print(x2_sub)

[[12  5]
 [ 7  6]]


In [249]:
x2_sub[0, 0] = 99 # modify subarray
print(x2_sub)

[[99  5]
 [ 7  6]]


In [250]:
print(x2) # same modification in x2

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


To explicitely copy the data within an array or subarray, copy() method can be used. Modifying the copied array will not affect the parent array.

In [251]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [252]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [253]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Array Reshaping

The most flexible way of
reshaping data is with the reshape() method.

Another common reshaping pattern is the conversion of a one-dimensional array
into a two-dimensional row or column matrix. This can be done by making use of the newaxis keyword within a slice operation.

In [254]:
# put the numbers 1 through 9 in a 3×3 grid
grid = np.arange(1, 10).reshape((3, 3))
print(grid)
# note: sizes of initial array must match size of reshaped array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [255]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [256]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [257]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

Concatenation, or joining of two arrays in NumPy, is primarily accomplished
through the routines np.concatenate, np.vstack, and np.hstack.

In [258]:
# np.concatenate takes a tuple or list of arrays as its first argument

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [259]:
# concatenate more than two arrays at once
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


np concatenate "stacks" NumPy arrays vertically or horizontally.

In [260]:
# np concatenate on two-dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [261]:
# concatenate along the first axis: axis=0 (default)
# axis=0 is the direction running vertically down the rows
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [262]:
# concatenate along the second axis (zero-indexed): axis=1
#  axis=1 is the direction running horizontally across the columns
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions.

In [263]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [264]:
# horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

np.dstack will stack arrays along the third axis.

The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, a list of indices giving the split points is passed.

In [265]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
# N split points lead to N + 1 subarrays
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [266]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [267]:
# vertical split
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [268]:
# horizontal split
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


np.dsplit will split arrays along the third axis.

## Computation on NumPy Arrays

Computation on NumPy arrays can be very fast, or it can be very slow. The key to making it fast is to use **vectorised operations**, generally implemented through NumPy’s universal functions (ufuncs). Vectorised functions push the loop into the compiled layer that underlies NumPy. Thereby, when performing an operation on the array, it will be applied to each element.

The reason for this is that Python is very slow when computing loops. This is in part due to the dynamic, interpreted nature of the language: the fact that types are flexible, so that sequences of operations cannot be compiled down to efficient machine code.



In [269]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

Unary ufuncs operate on a single input, and binary
ufuncs operate on two inputs.

In [270]:
# standard addition, subtraction, multiplication, and division 
# using operators
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [271]:
# negation, exponentiation, and modulus
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [272]:
# functions in NumPy implementing arithmetic operators
np.add(x, 2)

array([2, 3, 4, 5])

The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|


To determine the absolute value, built-in and np functions can be used.

In [273]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [274]:
# corresponding NumPy ufunc is np.absolute (alias np.abs)
np.absolute(x)

array([2, 1, 0, 1, 2])

NumPy also provides the trigonometric functions.

In [275]:
theta = np.linspace(0, np.pi, 3)

In [276]:
# compute some trigonometric functions on these values
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [277]:
# Inverse trigonometric functions
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


Another common type of operation available in a NumPy ufunc are the exponentials and logarithms.

In [278]:
# exponentials
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [279]:
# logarithms
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x)) # natural logarithm
print("log2(x) =", np.log2(x)) # base-2
print("log10(x) =", np.log10(x)) # base-10

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [280]:
# specialized versions useful for maintaining precision with small input
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


NumPy has many more ufuncs available, including hyperbolic trig functions, bitwise arithmetic, comparison operators, conversions from radians to degrees, rounding and
remainders, and much more (see NumPy documentation for details).

Another excellent source for more specialized and obscure ufuncs is the submodule *scipy.special*.

For large calculations, it is sometimes useful to be able to specify the array where the
result of the calculation will be stored to save results of computation directly to memory. 

In [281]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [282]:
# write the results of computation to every other element of a specified array
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


For binary ufuncs, there are some interesting aggregates that can be computed directly from the object.

For example, if we’d like to reduce an array with a particular operation, we can use the reduce method of any ufunc. A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

In [283]:
x = np.arange(1, 6)
# calling reduce on the add ufunc returns the sum of all elements in the array
np.add.reduce(x)

15

In [284]:
# results in the product of all array elements
np.multiply.reduce(x)

120

In [285]:
# to store all the intermediate results of the computation
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [286]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

Any ufunc can compute the output of all pairs of two different inputs using the outer method.

In [287]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

## Aggregations: Min, Max, and Everything in Between

NumPy can be used to compute summary statistics.

For instance, to compute the sum of an array, the built-in function sum or np.sum can be used.

However, np.sum is quicker because it executes compiled code.

In [288]:
L = np.random.random(100)
sum(L)

52.12818058833704

In [289]:
np.sum(L)

52.12818058833702

In [290]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

89 ms ± 2.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
389 µs ± 16.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Python has built-in min and max functions, used to find the minimum value and maximum value of any given array.

In [291]:
min(big_array), max(big_array)

(1.4057692298008462e-06, 0.9999994392723005)

NumPy’s corresponding functions have similar syntax and operate quicker.

In [292]:
np.min(big_array), np.max(big_array)

(1.4057692298008462e-06, 0.9999994392723005)

In [293]:
%timeit min(big_array)
%timeit np.min(big_array)

60.2 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
424 µs ± 4.39 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


For min, max, sum, and several other NumPy aggregates, a shorter syntax is to use methods of the array object itself.

In [294]:
print(big_array.min(), big_array.max(), big_array.sum())

1.4057692298008462e-06 0.9999994392723005 500202.5348847683


Aggregatiuon is possible along rows or columns. By default, each NumPy aggregation function will return the aggregate over the entire array.



In [295]:
M = np.random.random((3, 4))
print(M)

[[0.50063048 0.07383653 0.49018646 0.72521956]
 [0.84926562 0.10226215 0.99559424 0.59250301]
 [0.53509    0.88518089 0.25518136 0.13130483]]


In [296]:
# default: aggregate over entire array
M.sum()

6.1362551272647154

To aggregate across rows or columns, the axis argument can be used.

The axis keyword specifies the dimension of the array that will be collapsed, rather than the dimension that will be returned.

In [297]:
# minimum value in each column: axis=0 (vertical along rows)
M.min(axis=0)

array([0.50063048, 0.07383653, 0.25518136, 0.13130483])

In [298]:
# maximum value in each row: axis=1 (horizontal along columns)
M.max(axis=1)

array([0.72521956, 0.99559424, 0.88518089])

Other aggregation functions (including their NaN-safe versions) are listed below.

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |


## Example: What Is the Average Height of US Presidents?